import{makeScene,Renderer,sceneSVG,clamp}from'./engine.js?v=0.2.0';
import{generateImage,IMAGE_PROMPT,LINE_PROMPT}from'./gemini.js?v=0.2.0';
import{exportVideo,dimensions}from'./exporter.js?v=0.2.0';
const $=id=>document.getElementById(id),version=1;
const state={source:null,guide:null,trace:null,scene:null,image:null,renderer:null,time:0,view:'film',playing:false,busy:false,controller:null,downloadURL:null,name:'새 작품'};
const storage={get(k,f){try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true;}catch{return false;}},remove(k){try{localStorage.removeItem(k);}catch{}}};
let settings={provider:'direct',model:'gemini-3.1-flash-image',proxyUrl:'',key:'',password:'',...storage.get('linecinema.settings',{}),key:storage.get('linecinema.key',''),password:''};
function status(message,type=''){ $('status').textContent=message;$('status').className='status '+type; }
function controls(){const ready=!!state.scene;for(const id of ['play','export','saveProject','savePNG','saveSVG'])$(id).disabled=!ready||state.busy;for(const el of document.querySelectorAll('aside button,aside select,aside textarea,aside input,#resolution,#fps,#loadProject,#openSettings,#emptySample'))el.disabled=state.busy;$('cancel').hidden=!state.busy;$('progress').hidden=!state.busy;$('refine').disabled=!state.source||state.busy;$('retrace').disabled=!state.source||state.busy;}
function stop(){state.playing=false;$('play').textContent='▶';}
function busy(on){state.busy=on;if(on){stop();$('progress').value=0;}controls();}
async function job(fn){if(state.busy)return;state.controller=new AbortController();busy(true);try{await fn(state.controller.signal);}catch(error){if(error.name==='AbortError')status(error.message&&error.message!=='signal is aborted without reason'?error.message:'작업을 취소했습니다.');else status(error.message||String(error),'error');}finally{busy(false);state.controller=null;}}
function options(){return{aspect:$('aspect').value,fps:+$('fps').value,width:+$('width').value,pressure:+$('pressure').value,human:+$('human').value,duration:+$('duration').value,camera:$('camera').value,start:$('start').value,background:+$('background').value,pen:$('pen').checked};}
function formatTime(t){return`${String(Math.floor(t/60)).padStart(2,'0')}:${(t%60).toFixed(1).padStart(4,'0')}`;}
function readouts(){for(const id of ['pressure','human','background','detail'])$(id+'Value').value=$(id).value+'%';$('widthValue').value=(+$('width').value).toFixed(1);const duration=state.scene?.duration||+$('duration').value+7;$('seek').max=duration;$('total').textContent=formatTime(duration);$('callHint').textContent=$('pipeline').value==='art'?'이미지 생성 2회 · 이후 연출 변경은 추가 호출 없음':'이미지 생성 1회 · 이후 연출 변경은 추가 호출 없음';$('stageBadge').textContent=`${$('aspect').value} · ${$('fps').value} FPS`;}
function rebuild(){readouts();if(!state.trace)return;state.scene=makeScene(state.trace,options());$('seek').max=state.scene.duration;$('total').textContent=formatTime(state.scene.duration);$('timingNote').textContent=`펜을 떼지 않는 한 줄 · 드로잉 ${state.scene.options.duration}초 + 엔딩 7초${state.scene.options.duration>+$('duration').value?' · 급하게 그려지지 않도록 시간을 늘렸습니다.':''}`;$('strokeInfo').textContent=`연속선 1개 · 펜 들기 0회${state.scene.continuity.bridgeCount?' · 떨어진 윤곽 자동 연결':''}`;const[w,h]=dimensions($('aspect').value,540);$('preview').width=w;$('preview').height=h;$('preview').style.aspectRatio=`${w}/${h}`;state.renderer=new Renderer($('preview'),state.scene,state.image);state.time=Math.min(state.time,state.scene.duration);render();controls();}
function render(){if(!state.renderer)return;const result=state.renderer.render(state.time,state.view);$('phase').textContent=state.view==='final'?'완성 선화':state.view==='source'?'원본 이미지':result.phase;$('seek').value=state.time;$('time').textContent=formatTime(state.time);}
function setView(view){state.view=view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));render();}
let last=performance.now();function animate(now){if(state.playing&&state.scene){state.time=Math.min(state.scene.duration,state.time+Math.min(.04,(now-last)/1000));render();if(state.time>=state.scene.duration)stop();}last=now;requestAnimationFrame(animate);}requestAnimationFrame(animate);
const safeDataURL=s=>typeof s==='string'&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(s);
function loadImage(url){return new Promise((resolve,reject)=>{if(!safeDataURL(url)){reject(new Error('유효한 이미지 데이터가 아닙니다.'));return;}const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('이미지를 읽을 수 없습니다.'));img.src=url;});}
const fileData=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('파일을 읽지 못했습니다.'));reader.readAsDataURL(file);});
async function normalizeImage(url){const image=await loadImage(url);if(image.naturalWidth*image.naturalHeight>100000000)throw new Error('이미지가 너무 큽니다. 10000px 이하로 줄여 주세요.');const scale=Math.min(1,1800/Math.max(image.width,image.height));const c=document.createElement('canvas');c.width=Math.round(image.width*scale);c.height=Math.round(image.height*scale);const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(image,0,0,c.width,c.height);return c.toDataURL('image/png');}
async function traceImage(url,signal,mode){const img=await loadImage(url),s=Math.min(1,1100/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(16,Math.round(img.width*s));canvas.height=Math.max(16,Math.round(img.height*s));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);const pixels=ctx.getImageData(0,0,canvas.width,canvas.height).data;return new Promise((resolve,reject)=>{const worker=new Worker(new URL('./trace-worker.js?v=0.2.0',import.meta.url)),finish=(error,result)=>{worker.terminate();clearTimeout(timeout);signal?.removeEventListener('abort',abort);error?reject(error):resolve(result);},abort=()=>finish(new DOMException('선 추출을 취소했습니다.','AbortError')),timeout=setTimeout(()=>finish(new Error('선 추출에 시간이 너무 오래 걸립니다. 사진 크기나 세부 묘사를 줄여 주세요.')),90000);signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted){abort();return;}worker.onmessage=e=>{if(e.data.error)finish(new Error(e.data.error));else if(e.data.result)finish(null,e.data.result);else if(e.data.stage)status(e.data.stage);};worker.onerror=e=>finish(new Error(e.message||'선 추출 작업에 실패했습니다.'));worker.postMessage({pixels,width:canvas.width,height:canvas.height,mode:mode||$('traceMode').value,detail:+$('detail').value},[pixels.buffer]);});}
async function install(source,guide,name,signal,mode){status('그림의 선을 분석하고 있습니다.');const trace=await traceImage(guide||source,signal,mode);if(signal?.aborted)throw new DOMException('작업을 취소했습니다.','AbortError');const img=await loadImage(source);state.source=source;state.guide=guide;state.trace=trace;state.image=img;state.name=name;state.time=0;setView('film');$('empty').hidden=true;$('sourceStrip').hidden=false;$('sourceThumb').src=source;$('sourceLabel').textContent=name;$('strokeInfo').textContent=`${trace.paths.length.toLocaleString()}개 획 · ${trace.mode==='line'?'선화':'사진'} 분석`;rebuild();await autosave();status(`펜을 떼지 않는 한 줄 경로를 준비했습니다. 재생해서 선의 흐름을 확인하세요.`,'success');}
function credentials(){if(settings.provider==='direct'&&!settings.key||settings.provider==='proxy'&&(!settings.proxyUrl||!settings.password)){openSettings();status('먼저 연결 설정을 입력해 주세요.');return false;}return true;}
$('generate').onclick=()=>{if(!credentials())return;const prompt=$('prompt').value.trim();if(!prompt){status('어떤 그림인지 설명해 주세요.','error');return;}job(async signal=>{const art=$('pipeline').value==='art';status(art?'1/2 · Gemini가 원본 그림을 생성하고 있습니다.':'Gemini가 선화를 생성하고 있습니다.');const source=await generateImage({settings,prompt:art?IMAGE_PROMPT.replace('{SUBJECT}',prompt):`Create a true ONE CONTINUOUS LINE drawing of: ${prompt}. Imagine one pen touching the paper once and drawing the entire subject without ever lifting. Every detail must connect to the same unbroken line. Integrate separate objects and interior details through short natural contour connections, allowing subtle retracing. No isolated marks, dots or disconnected outlines. Sparse elegant black ink on pure white, no shading, fill regions, hatching or text. Full composition with generous margins.`,aspect:$('aspect').value,signal});$('progress').value=.45;if(!art){await install(source,source,'Gemini 선화',signal,'line');return;}let guide;try{status('2/2 · 같은 구도로 간결한 선화를 만들고 있습니다.');guide=await generateImage({settings,prompt:LINE_PROMPT,image:source,aspect:$('aspect').value,signal});}catch(e){ // Keep a paid first image even if the second call fails or is cancelled.
await install(source,null,'Gemini 원본',undefined,'photo');status(`원본은 보존했습니다. AI 선화 정리는 완료되지 않았습니다. ${e.name==='AbortError'?'요청을 취소했습니다.':e.message} 현재는 기기에서 추출한 선으로 미리보기합니다. 필요하면 ‘AI 선화 정리’를 다시 눌러 주세요.`,'error');return;}await install(source,guide,'Gemini 그림 + 선화',signal,'line');});};
$('refine').onclick=()=>{if(!state.source||!credentials())return;job(async signal=>{status('Gemini가 원본과 같은 구도의 선화를 만들고 있습니다. · 이미지 생성 1회');const guide=await generateImage({settings,prompt:LINE_PROMPT,image:state.source,aspect:$('aspect').value,signal});await install(state.source,guide,'AI로 정리한 선화',signal,'line');});};
$('uploadBtn').onclick=()=>$('imageFile').click();$('imageFile').onchange=e=>{const file=e.target.files[0];e.target.value='';if(!file)return;job(async signal=>{if(file.size>25*1024*1024)throw new Error('25MB 이하의 PNG, JPG, WebP를 사용해 주세요.');if(!/^image\/(png|jpeg|webp)$/.test(file.type))throw new Error('PNG, JPG, WebP 이미지를 사용해 주세요.');const data=await normalizeImage(await fileData(file));await install(data,null,file.name,signal);});};
async function sample(){await job(async signal=>{const response=await fetch(new URL('../assets/reference-study.jpg',import.meta.url),{signal});if(!response.ok)throw new Error('예시 이미지를 불러오지 못했습니다.');const data=await fileData(await response.blob());await install(data,data,'참고 영상 연구 · @crisd.singleline',signal,'line');status('첨부 영상의 완성 장면으로 만든 동작 예시입니다. 새 작품은 그림 생성 또는 이미지 불러오기로 시작하세요.','success');});}
$('sampleBtn').onclick=sample;$('emptySample').onclick=sample;
$('retrace').onclick=()=>{if(state.source)job(signal=>install(state.source,state.guide,state.name,signal));};
$('play').onclick=()=>{if(!state.scene||state.busy)return;if(state.playing){stop();return;}if(state.time>=state.scene.duration)state.time=0;setView('film');state.playing=true;last=performance.now();$('play').textContent='Ⅱ';};
$('restart').onclick=()=>{stop();state.time=0;setView('film');};$('seek').oninput=()=>{stop();state.time=+$('seek').value;setView('film');};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{stop();setView(b.dataset.view);});
let debounce;for(const id of ['width','pressure','human','duration','camera','start','background','pen','aspect','fps'])$(id).addEventListener('input',()=>{stop();readouts();clearTimeout(debounce);debounce=setTimeout(()=>{rebuild();autosave();},120);});$('detail').oninput=readouts;$('pipeline').onchange=readouts;$('fps').onchange=()=>{readouts();};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
const stamp=()=>new Date().toISOString().replace(/[:.]/g,'-').slice(0,19);
$('export').onclick=()=>job(async signal=>{clearTimeout(debounce);rebuild();if(!state.scene)throw new Error('먼저 그림을 준비해 주세요.');let wake;try{wake=await navigator.wakeLock?.request('screen');}catch{}try{status('영상 인코더를 준비하고 있습니다.');const result=await exportVideo(state.scene,state.image,{aspect:$('aspect').value,resolution:+$('resolution').value,fps:+$('fps').value,signal,onProgress:(p,message)=>{$('progress').value=p;status(`${message} ${Math.round(p*100)}%`);}});if(state.downloadURL)URL.revokeObjectURL(state.downloadURL);state.downloadURL=URL.createObjectURL(result.blob);const a=$('downloadLink');a.href=state.downloadURL;a.download=`LineCinema-${stamp()}.${result.extension}`;a.textContent=`${result.extension.toUpperCase()} 다시 다운로드`;a.hidden=false;a.click();status(`${result.extension.toUpperCase()} 저장 완료 · ${state.scene.duration}초 · ${(result.blob.size/1048576).toFixed(1)}MB${result.extension==='webm'?' · 이 브라우저는 MP4 인코딩을 지원하지 않아 WebM으로 저장했습니다.':''}`,'success');}finally{await wake?.release().catch(()=>{});}});
$('cancel').onclick=()=>state.controller?.abort();
$('savePNG').onclick=()=>{if(!state.scene)return;const canvas=document.createElement('canvas'),[w,h]=dimensions($('aspect').value,1080);canvas.width=w;canvas.height=h;new Renderer(canvas,state.scene,state.image).render(state.scene.duration,'final');canvas.toBlob(blob=>blob&&download(blob,`LineCinema-${stamp()}.png`));};
$('saveSVG').onclick=()=>state.scene&&download(new Blob([sceneSVG(state.scene)],{type:'image/svg+xml'}),`LineCinema-${stamp()}.svg`);
function project(){return{app:'JNB-Line-Cinema',version,name:state.name,prompt:$('prompt').value,source:state.source,guide:state.guide,trace:state.trace,options:options(),detail:+$('detail').value,traceMode:$('traceMode').value};}
$('saveProject').onclick=()=>download(new Blob([JSON.stringify(project())],{type:'application/json'}),`LineCinema-${stamp()}.linecinema`);
$('loadProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=e=>{const file=e.target.files[0];e.target.value='';if(!file)return;job(async()=>{if(file.size>60*1048576)throw new Error('60MB 이하의 프로젝트를 사용해 주세요.');let data;try{data=JSON.parse(await file.text());}catch{throw new Error('프로젝트 파일 형식을 확인해 주세요.');}await restore(data);await autosave();status('프로젝트를 복원했습니다.','success');});};
function validateProject(p){if(p?.app!=='JNB-Line-Cinema'||p.version!==1||!safeDataURL(p.source)||p.guide&&!safeDataURL(p.guide))throw new Error('지원하지 않는 프로젝트입니다.');const t=p.trace;if(!t||!Array.isArray(t.paths)||!t.paths.length||t.paths.length>4500||![t.width,t.height].every(n=>Number.isFinite(n)&&n>=16&&n<=2000))throw new Error('프로젝트의 선 데이터가 올바르지 않습니다.');let count=0;for(const path of t.paths){if(!Array.isArray(path)||path.length<2||path.length>200000)throw new Error('잘못된 획입니다.');count+=path.length;if(count>1000000)throw new Error('선 데이터가 너무 큽니다.');for(const point of path)if(!Array.isArray(point)||point.length!==2||!point.every((n,i)=>Number.isFinite(n)&&n>=0&&n<=(i?t.height:t.width)))throw new Error('잘못된 선 좌표입니다.');}const b=t.bounds;if(!b||![b.x,b.y,b.w,b.h].every(Number.isFinite)||b.w<=0||b.h<=0||b.x<0||b.y<0||b.x+b.w>t.width+1||b.y+b.h>t.height+1)throw new Error('잘못된 그림 영역입니다.');return p;}
async function restore(data){const p=validateProject(data),img=await loadImage(p.source);for(const id of ['width','pressure','human','duration','camera','start','background','aspect','fps'])if(p.options?.[id]!=null){const el=$(id),value=String(p.options[id]);if(el.tagName==='SELECT'){if([...el.options].some(o=>o.value===value))el.value=value;}else if(Number.isFinite(+value))el.value=clamp(+value,+el.min,+el.max);}$('pen').checked=p.options?.pen!==false;$('prompt').value=String(p.prompt||'').slice(0,12000);if(Number.isFinite(p.detail))$('detail').value=clamp(p.detail,10,90);if(['auto','line','photo'].includes(p.traceMode))$('traceMode').value=p.traceMode;Object.assign(state,{source:p.source,guide:p.guide||null,trace:p.trace,image:img,name:String(p.name||'저장된 작품').slice(0,150),time:0});$('empty').hidden=true;$('sourceStrip').hidden=false;$('sourceThumb').src=state.source;$('sourceLabel').textContent=state.name;$('strokeInfo').textContent=`${state.trace.paths.length.toLocaleString()}개 획 · 복원됨`;setView('film');rebuild();}
let database;function db(){if(database)return database;database=new Promise((resolve,reject)=>{const req=indexedDB.open('JNB-Line-Cinema',1);req.onupgradeneeded=()=>req.result.createObjectStore('projects');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});return database;}
async function autosave(){if(!state.trace)return;try{const database=await db(),tx=database.transaction('projects','readwrite');tx.objectStore('projects').put(project(),'current');await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}catch{status('자동 저장 공간이 부족하거나 사용할 수 없습니다. ‘프로젝트 저장’으로 파일을 보관해 주세요.','error');}}
async function autoload(){try{const database=await db(),req=database.transaction('projects').objectStore('projects').get('current'),data=await new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});if(data&&!state.trace&&!state.busy){await restore(data);status('이 브라우저에서 마지막으로 작업한 그림을 복원했습니다.');}}catch{}}
function connectionUI(){$('connectionLabel').textContent=settings.provider==='proxy'?'Cloudflare':settings.key?'키 입력됨':'API 키 필요';}
function fields(){$('directFields').hidden=$('provider').value!=='direct';$('proxyFields').hidden=$('provider').value!=='proxy';}
function openSettings(){for(const[id,key]of [['provider','provider'],['apiKey','key'],['model','model'],['proxyUrl','proxyUrl'],['proxyPassword','password']])$(id).value=settings[key]||'';$('remember').checked=storage.get('linecinema.remember',true);fields();if(!$('settings').open)$('settings').showModal();}
$('openSettings').onclick=openSettings;$('closeSettings').onclick=()=>$('settings').close();$('provider').onchange=fields;
$('settingsForm').onsubmit=e=>{e.preventDefault();settings={provider:$('provider').value,key:$('apiKey').value.trim(),model:$('model').value.trim()||'gemini-3.1-flash-image',proxyUrl:$('proxyUrl').value.trim(),password:$('proxyPassword').value};const ok=storage.set('linecinema.settings',{provider:settings.provider,model:settings.model,proxyUrl:settings.proxyUrl});storage.set('linecinema.remember',$('remember').checked);let stored=true;if($('remember').checked&&settings.key)stored=storage.set('linecinema.key',settings.key);else storage.remove('linecinema.key');connectionUI();$('settings').close();status(ok&&stored?'연결 설정을 적용했습니다. API 호출은 그림 생성 시에만 이루어집니다.':'설정은 적용했지만 브라우저 저장이 차단되어 현재 탭에서만 사용합니다.');};
$('forget').onclick=()=>{storage.remove('linecinema.key');settings.key='';$('apiKey').value='';$('remember').checked=false;connectionUI();status('이 브라우저에 저장한 API 키를 삭제했습니다.');};
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','TEXTAREA','SELECT','BUTTON'].includes(e.target.tagName)&&!$('settings').open){e.preventDefault();$('play').click();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
// Optional browser-native agent access: read-only state and a reversible preview seek.
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'inspect_line_cinema',description:'현재 작품의 연속 경로, 시간과 연출 설정을 읽습니다. API 키는 반환하지 않습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({ready:!!state.scene,strokes:state.scene?1:0,penLifts:state.scene?0:null,duration:state.scene?.duration||0,time:state.time,options:options()})});document.modelContext.registerTool({name:'seek_line_cinema_preview',description:'드로잉 영상 미리보기의 재생 위치를 이동합니다. 생성이나 다운로드는 하지 않습니다.',inputSchema:{type:'object',properties:{seconds:{type:'number',minimum:0}},required:['seconds'],additionalProperties:false},execute:input=>{if(!state.scene||state.busy||!Number.isFinite(input?.seconds)||input.seconds<0||input.seconds>state.scene.duration)throw new Error('준비된 영상 범위 안의 시간을 입력해 주세요.');stop();state.time=input.seconds;setView('film');return{seconds:state.time};}});}catch{}}
connectionUI();readouts();controls();autoload();
