export const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
const mix=(a,b,t)=>a+(b-a)*t;
const ease=t=>{t=clamp(t);return t*t*t*(t*(t*6-15)+10);};
const distance=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
const noise=(n)=>{const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x);};
function smoothResample(pts,human,seed){ // Preserve hard corners, smooth pixel stair-steps, then sample at ~1.6 analysis pixels.
 const clean=pts.map((p,i)=>{if(!i||i===pts.length-1)return p.slice();const a=pts[i-1],b=pts[i+1],v1=[p[0]-a[0],p[1]-a[1]],v2=[b[0]-p[0],b[1]-p[1]],cos=(v1[0]*v2[0]+v1[1]*v2[1])/(Math.hypot(...v1)*Math.hypot(...v2)||1),f=cos>.3?.16:.04;return[p[0]*(1-2*f)+(a[0]+b[0])*f,p[1]*(1-2*f)+(a[1]+b[1])*f];});
 const out=[clean[0]],lengths=[0];let length=0;for(let i=1;i<clean.length;i++){const a=clean[i-1],b=clean[i],d=distance(a,b),steps=Math.max(1,Math.ceil(d/1.6));for(let j=1;j<=steps;j++){const t=j/steps,s=length+d*t,drift=(Math.sin(s*.035+seed)*.22+Math.sin(s*.12+seed*2)*.09)*human,nx=-(b[1]-a[1])/(d||1),ny=(b[0]-a[0])/(d||1);out.push([mix(a[0],b[0],t)+nx*drift,mix(a[1],b[1],t)+ny*drift]);lengths.push(s);}length+=d;}return{points:out,lengths,length};
}
export function makeScene(trace,options){options={...options,requestedDuration:options.duration};const b=trace.bounds;const localPaths=[];for(const path of trace.paths){let chunk=[path[0]],length=0;for(let j=1;j<path.length;j++){length+=distance(path[j-1],path[j]);chunk.push(path[j]);if(length>Math.max(30,Math.max(b.w,b.h)*.22)&&j<path.length-1){localPaths.push(chunk);chunk=[path[j]];length=0;}}if(chunk.length>1)localPaths.push(chunk);}let raw=localPaths.map((points,i)=>{const center=points.reduce((a,p)=>[a[0]+p[0]/points.length,a[1]+p[1]/points.length],[0,0]);return{points:points.map(p=>p.slice()),center,i};});
 // Spatial bands keep the nib and camera in one region. Lower regions reveal before upper ones.
 const key=s=>{let x=clamp((s.center[0]-b.x)/b.w,0,.999),y=clamp((s.center[1]-b.y)/b.h,0,.999);const row=options.start==='left'?Math.floor(x*4):options.start==='top'?Math.floor(y*4):Math.min(3,Math.floor((1-y)*4)),col=options.start==='left'?Math.floor(y*3):Math.floor(x*3);return row*3+(row%2?2-col:col);};
 const buckets=new Map();for(const s of raw){const k=key(s);if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(s);}const ordered=[];let prev=[b.x+b.w*.2,b.y+b.h];for(const k of [...buckets.keys()].sort((a,b)=>a-b)){const group=buckets.get(k);while(group.length){let best=0,reverse=false,score=Infinity;for(let i=0;i<group.length;i++){const p=group[i].points,a=distance(prev,p[0]),z=distance(prev,p.at(-1));if(Math.min(a,z)<score){score=Math.min(a,z);best=i;reverse=z<a;}}const s=group.splice(best,1)[0];if(reverse)s.points.reverse();ordered.push(s);prev=s.points.at(-1);}}
 const strokes=ordered.map(s=>({...smoothResample(s.points,options.human/100,s.i+1),seed:s.i+1,center:s.center}));let pauseTotal=0,weightTotal=0;prev=strokes[0]?.points[0]||[0,0];for(const s of strokes){const gap=distance(prev,s.points[0]);s.pause=.018+Math.pow(gap/Math.max(b.w,b.h),1.1)*2.8;s.weight=s.length*(.85+noise(s.seed)*.3)+8;pauseTotal+=s.pause;weightTotal+=s.weight;prev=s.points.at(-1);}let cursor=0;const pauseShare=.24+options.human/100*.08,minFrames=4,fps=options.fps||30;let baseTotal=0;for(const s of strokes){s.minimumSeconds=Math.max(.12,minFrames/fps)+s.length/Math.max(b.w,b.h)*.7;baseTotal+=s.minimumSeconds;}options.duration=Math.max(options.duration,Math.ceil(baseTotal/(1-pauseShare)));const extra=Math.max(0,options.duration*(1-pauseShare)-baseTotal);for(const s of strokes){s.start=cursor+s.pause/pauseTotal*options.duration*pauseShare;s.end=s.start+s.minimumSeconds+s.weight/weightTotal*extra;cursor=s.end; // Slow down at curvature; travel and drawing have separate clocks.
 s.times=[0];let weight=0;for(let i=1;i<s.points.length;i++){const d=s.lengths[i]-s.lengths[i-1];let curvature=0;if(i>1){const a=s.points[i-2],p=s.points[i-1],q=s.points[i],v=[p[0]-a[0],p[1]-a[1]],u=[q[0]-p[0],q[1]-p[1]];curvature=1-clamp((v[0]*u[0]+v[1]*u[1])/(Math.hypot(...v)*Math.hypot(...u)||1),-1,1);}weight+=d*(1+options.human/100*(curvature*.6+.13*Math.sin(s.lengths[i]*.07+s.seed)));s.times.push(weight);}s.times=s.times.map(v=>v/(weight||1));}
 const scene={...trace,strokes,options,duration:options.duration+7};scene.cameraTrack=buildCamera(scene);return scene;}
function activeAt(scene,t){let lo=0,hi=scene.strokes.length;while(lo<hi){const m=(lo+hi)>>1;if(scene.strokes[m].end<t)lo=m+1;else hi=m;}return Math.min(lo,scene.strokes.length-1);}
export function tipAt(scene,t){const i=activeAt(scene,t),s=scene.strokes[i];if(!s)return{x:0,y:0,drawing:false,index:0};if(t<s.start){const prev=scene.strokes[Math.max(0,i-1)],from=i?prev.points.at(-1):s.points[0],to=s.points[0],f=ease((t-(i?prev.end:0))/(s.start-(i?prev.end:0)||1));return{x:mix(from[0],to[0],f),y:mix(from[1],to[1],f),drawing:false,index:i};}const f=clamp((t-s.start)/(s.end-s.start));let j=lowerBound(s.times,f),a=Math.max(0,j-1),k=(f-s.times[a])/(s.times[j]-s.times[a]||1);return{x:mix(s.points[a][0],s.points[j][0],k),y:mix(s.points[a][1],s.points[j][1],k),drawing:t<=scene.options.duration,index:i};}
function lowerBound(a,x){let l=0,r=a.length-1;while(l<r){const m=(l+r)>>1;if(a[m]<x)l=m+1;else r=m;}return l;}
function buildCamera(scene){const track=[],dt=1/30,d=scene.options.duration,b=scene.bounds;let tip=tipAt(scene,0),x=tip.x,y=tip.y;for(let t=0;t<=d+.05;t+=dt){const aim=tipAt(scene,Math.min(d,t+.25));x=mix(x,aim.x,.12);y=mix(y,aim.y,.12);track.push({x,y});} // Forward/backward filtering removes jitter without random frame-dependent motion.
for(let pass=0;pass<2;pass++){for(let i=track.length-2;i>=0;i--){track[i].x=mix(track[i].x,track[i+1].x,.55);track[i].y=mix(track[i].y,track[i+1].y,.55);}}const o=scene.options,ratio=(o.aspect||'9:16').split(':').map(Number),fit=Math.min(ratio[0]/(b.w*1.18),ratio[1]/(b.h*1.18));const required=track.map((c,i)=>{const t=Math.min(d,i/30),tip=tipAt(scene,t),p=t/d,base=o.camera==='mystery'?mix(3.6,1.85,ease(p)):mix(2,1.35,ease(p));return Math.min(base,ratio[0]*.41/(fit*(Math.abs(tip.x-c.x)+1)),ratio[1]*.41/(fit*(Math.abs(tip.y-c.y)+1)));});for(let i=0;i<track.length;i++){let zoom=required[i];for(let j=Math.max(0,i-60);j<=Math.min(track.length-1,i+60);j++)zoom=Math.min(zoom,required[j]+Math.abs(i-j)*.018);track[i].zoom=zoom;}return track;}
export function cameraAt(scene,t){const{options:o,bounds:b}=scene,center={x:b.x+b.w/2,y:b.y+b.h/2};if(o.camera==='fixed'||t>=o.duration+4)return{...center,zoom:1,rotation:0};const p=clamp(t/o.duration),i=clamp(t*30,0,scene.cameraTrack.length-1),a=scene.cameraTrack[Math.floor(i)],z=scene.cameraTrack[Math.min(Math.floor(i)+1,scene.cameraTrack.length-1)],f=i%1,zoom=o.camera==='mystery'?mix(3.6,1.85,ease(p)):mix(2,1.35,ease(p));const cam={x:mix(a.x,z.x,f),y:mix(a.y,z.y,f),zoom,rotation:o.camera==='mystery'?(Math.sin(p*Math.PI*1.4)*.022-.014):0};cam.zoom=mix(a.zoom,z.zoom,f);if(t>o.duration){const r=ease((t-o.duration)/4);cam.x=mix(cam.x,center.x,r);cam.y=mix(cam.y,center.y,r);cam.zoom=mix(cam.zoom,1,r);cam.rotation*=1-r;}return cam;}
function widths(s,o){return s.points.map((p,i)=>{const f=s.lengths[i]/(s.length||1),taper=Math.pow(Math.min(1,f/.1,(1-f)/.13),.6),slow=.78+.2*Math.sin(f*Math.PI)+.12*Math.sin(f*11+s.seed)+.06*Math.sin(f*27+s.seed*2),pressure=mix(1,(.15+.85*taper)*slow,o.pressure/100);return o.width*pressure*(.83+noise(s.seed)*.35);});}
export function ribbon(s,o,f=1){const ws=s.widths||(s.widths=widths(s,o)),index=lowerBound(s.times,clamp(f)),points=s.points.slice(0,index),radii=ws.slice(0,index).map(w=>w/2);if(index===0){points.push(s.points[0]);radii.push(ws[0]/2);}else{const a=index-1,k=(f-s.times[a])/(s.times[index]-s.times[a]||1);points.push([mix(s.points[a][0],s.points[index][0],k),mix(s.points[a][1],s.points[index][1],k)]);radii.push(mix(ws[a],ws[index],k)/2);}if(points.length<2)return[];const left=[],right=[];for(let i=0;i<points.length;i++){const a=points[Math.max(0,i-1)],b=points[Math.min(points.length-1,i+1)],d=distance(a,b)||1,nx=-(b[1]-a[1])/d,ny=(b[0]-a[0])/d;left.push([points[i][0]+nx*radii[i],points[i][1]+ny*radii[i]]);right.push([points[i][0]-nx*radii[i],points[i][1]-ny*radii[i]]);}return[...left,...right.reverse()];}
export function polygonPath(points){const p=new Path2D();if(points.length){p.moveTo(...points[0]);for(let i=1;i<points.length;i++)p.lineTo(...points[i]);p.closePath();}return p;}
export class Renderer{
 constructor(canvas,scene,image){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.scene=scene;this.image=image;this.paths=scene.strokes.map(s=>polygonPath(ribbon(s,scene.options)));this.resetCache();}
 resetCache(){const s=this.scene;this.cache=document.createElement('canvas');this.cacheScale=Math.min(2,3000/Math.max(s.width,s.height));this.cache.width=Math.ceil(s.width*this.cacheScale);this.cache.height=Math.ceil(s.height*this.cacheScale);this.cacheCtx=this.cache.getContext('2d');this.cacheCtx.scale(this.cacheScale,this.cacheScale);this.cacheCtx.fillStyle='#18191d';this.cached=0;}
 render(t,view='film'){const c=this.ctx,{width:W,height:H}=this.canvas,s=this.scene,o=s.options,b=s.bounds;const final=view==='final',source=view==='source';if(final)t=s.duration;const fullCount=source?0:activeAt(s,t)+(t>=o.duration?1:0);if(fullCount<this.cached){this.cacheCtx.clearRect(0,0,s.width,s.height);this.cached=0;}while(this.cached<fullCount&&this.cached<s.strokes.length){this.cacheCtx.fill(this.paths[this.cached]);this.cached++;}c.setTransform(1,0,0,1,0,0);c.fillStyle='#fff';c.fillRect(0,0,W,H);const cam=source?{x:b.x+b.w/2,y:b.y+b.h/2,zoom:1,rotation:0}:cameraAt(s,t),scale=Math.min(W/(b.w*1.18),H/(b.h*1.18))*cam.zoom;
 c.save();c.translate(W/2,H/2);c.rotate(cam.rotation);c.scale(scale,scale);c.translate(-cam.x,-cam.y);const alpha=source?1:(o.background/100)*(1-ease((t-o.duration)/3));if(this.image&&alpha>0&&!final){c.globalAlpha=alpha;c.drawImage(this.image,0,0,s.width,s.height);c.globalAlpha=1;}if(!source){c.drawImage(this.cache,0,0,s.width,s.height);if(t<o.duration){const st=s.strokes[fullCount];if(st&&t>st.start){const p=clamp((t-st.start)/(st.end-st.start));c.fillStyle='#18191d';c.fill(polygonPath(ribbon(st,o,p)));}}}c.restore();
 if(!source&&!final&&o.pen&&t<o.duration){const p=tipAt(s,t),dx=(p.x-cam.x)*scale,dy=(p.y-cam.y)*scale,x=W/2+dx*Math.cos(cam.rotation)-dy*Math.sin(cam.rotation),y=H/2+dx*Math.sin(cam.rotation)+dy*Math.cos(cam.rotation);c.save();c.translate(x,y);c.rotate(-.72);const z=W/540;c.scale(z,z);c.globalAlpha=p.drawing?.85:.32;c.beginPath();c.moveTo(0,0);c.lineTo(3,-12);c.lineTo(7,-12);c.closePath();c.fillStyle='#252630';c.fill();c.beginPath();c.moveTo(5,-11);c.lineTo(8,-37);c.lineWidth=5;c.strokeStyle='#afb1ba';c.lineCap='round';c.stroke();c.restore();}
 return{phase:t<o.duration?'디테일 드로잉':t<o.duration+4?'전체 공개':'완성 선화 · 3초',backgroundAlpha:alpha,cam};}
}
export function sceneSVG(scene){const b=scene.bounds,pad=Math.max(b.w,b.h)*.06;return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${b.x-pad} ${b.y-pad} ${b.w+pad*2} ${b.h+pad*2}"><rect x="${b.x-pad}" y="${b.y-pad}" width="${b.w+pad*2}" height="${b.h+pad*2}" fill="white"/><g fill="#18191d">${scene.strokes.map(s=>`<path d="${ribbon(s,scene.options).map((p,i)=>(i?'L':'M')+p.map(n=>n.toFixed(2)).join(' ')).join('')}Z"/>`).join('')}</g></svg>`;}
