import{Renderer}from'./engine.js?v=0.3.3';
import{muxMP4}from'./mp4.js';
export function dimensions(aspect,short=1080){const[a,b]=aspect.split(':').map(Number);if(a===b)return[short,short];return a>b?[Math.round(short*a/b/2)*2,short]:[short,Math.round(short*b/a/2)*2];}
const tick=()=>new Promise(r=>setTimeout(r,0));
function aborted(signal){if(signal?.aborted)throw new DOMException('작업을 취소했습니다.','AbortError');}
async function configFor(w,h,fps){if(!globalThis.VideoEncoder||!globalThis.VideoFrame)return null;for(const codec of ['avc1.42002a','avc1.4d002a']){const config={codec,width:w,height:h,framerate:fps,bitrate:Math.round(w*h*fps*.14),latencyMode:'realtime',avc:{format:'avc'}};try{if((await VideoEncoder.isConfigSupported(config)).supported)return config;}catch{}}return null;}
export async function exportVideo(scene,image,{aspect,resolution,fps,signal,onProgress}){const[w,h]=dimensions(aspect,resolution),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const renderer=new Renderer(canvas,scene,image),config=await configFor(w,h,fps);aborted(signal);if(config)return encodeMP4(renderer,config,fps,signal,onProgress);return recordVideo(renderer,fps,signal,onProgress);}
async function encodeMP4(renderer,config,fps,signal,onProgress){const frames=Math.round(renderer.scene.duration*fps),samples=[];let avcc,error;const encoder=new VideoEncoder({output(chunk,meta){const data=new Uint8Array(chunk.byteLength);chunk.copyTo(data);samples.push({data,key:chunk.type==='key',timestamp:chunk.timestamp});if(meta?.decoderConfig?.description)avcc=new Uint8Array(meta.decoderConfig.description).slice();},error:e=>{error=e;}});try{encoder.configure(config);for(let i=0;i<frames;i++){aborted(signal);if(error)throw error;while(encoder.encodeQueueSize>5){await tick();aborted(signal);if(error)throw error;}renderer.render(i/fps);const frame=new VideoFrame(renderer.canvas,{timestamp:Math.round(i*1e6/fps),duration:Math.round((i+1)*1e6/fps)-Math.round(i*1e6/fps)});try{encoder.encode(frame,{keyFrame:i%(fps*2)===0});}finally{frame.close();}if(i%8===0){onProgress(i/frames,'MP4 · 프레임을 저장하고 있습니다.');await tick();}}await encoder.flush();aborted(signal);if(error)throw error;samples.sort((a,b)=>a.timestamp-b.timestamp);if(samples.length!==frames)throw new Error('영상 프레임 수가 일치하지 않습니다.');const blob=muxMP4(samples,avcc,config.width,config.height,fps);onProgress(1,'MP4 영상이 완성되었습니다.');return{blob,extension:'mp4',method:'WebCodecs',frames};}finally{if(encoder.state!=='closed')encoder.close();}}
async function recordVideo(renderer,fps,signal,onProgress){if(!globalThis.MediaRecorder||!renderer.canvas.captureStream)throw new Error('이 브라우저는 영상 저장을 지원하지 않습니다. 최신 Chrome 또는 Edge에서 열어 주세요.');const types=['video/mp4;codecs=avc1.42E01E','video/mp4','video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'],mime=types.find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw new Error('사용 가능한 영상 인코더가 없습니다.');const ext=mime.includes('mp4')?'mp4':'webm';onProgress(0,`${ext.toUpperCase()} 실시간 저장 · 이 탭을 계속 열어 두세요.`);renderer.render(0);const stream=renderer.canvas.captureStream(fps),recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:12000000}),chunks=[];let raf,rejectRun,stopped=false,hidden=false;const cancel=()=>{if(!stopped){stopped=true;cancelAnimationFrame(raf);if(recorder.state!=='inactive')recorder.stop();rejectRun?.(new DOMException(hidden?'다른 탭으로 이동해 녹화를 중단했습니다. 이 탭을 열어 둔 상태로 다시 저장해 주세요.':'작업을 취소했습니다.','AbortError'));}};const visibility=()=>{if(document.hidden){hidden=true;cancel();}};const completion=new Promise((resolve,reject)=>{rejectRun=reject;recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onerror=e=>reject(e.error||new Error('녹화에 실패했습니다.'));recorder.onstop=()=>{if(!stopped)resolve();};});signal?.addEventListener('abort',cancel,{once:true});document.addEventListener('visibilitychange',visibility);try{recorder.start(1000);const start=performance.now(),duration=renderer.scene.duration;const draw=now=>{if(stopped)return;const t=(now-start)/1000;renderer.render(Math.min(t,duration));onProgress(Math.min(1,t/duration),`${ext.toUpperCase()} 실시간 저장 · 탭을 유지해 주세요.`);if(t<duration)raf=requestAnimationFrame(draw);else recorder.stop();};raf=requestAnimationFrame(draw);await completion;aborted(signal);return{blob:new Blob(chunks,{type:mime}),extension:ext,method:'MediaRecorder'};}finally{cancelAnimationFrame(raf);signal?.removeEventListener('abort',cancel);document.removeEventListener('visibilitychange',visibility);if(recorder.state!=='inactive')recorder.stop();stream.getTracks().forEach(t=>t.stop());}}
