export const IMAGE_PROMPT=`Create one refined reference image for a pen-drawing film. Subject: {SUBJECT}. The entire subject must fit in the frame with a generous white margin. Use a clear, readable silhouette and quiet off-white background. Carefully compose the main objects, limbs, clothing folds and props. Soft monochrome editorial photograph aesthetic, clear contours, no clutter or dense textures. No text, letters, labels, frames, collage, signature, or multiple panels. Return an image.`;
export const LINE_PROMPT=`Transform the supplied reference into a minimalist black ink contour drawing on pure white. Preserve EXACT composition, position, scale, proportions, pose and silhouette of every main object in the input. Do not crop, zoom, rearrange, add or remove main objects. Use a deliberately sparse drawing: only the outer silhouette and a very few defining interior contours. Omit skin texture, tiny fabric wrinkles, hair strands, repeated furniture seams, background texture and decorative micro-details. Leave large areas completely empty. Draw only thoughtful essential contours and a few expressive interior lines, using ONE genuinely continuous unbroken line, as if a single pen never leaves the paper. Every object and interior detail must belong to the same connected line. Strongly prefer connections along existing contact points, shared ground contours or furniture. Preserve all main subjects. If they cannot be connected naturally, use the fewest short unobtrusive connecting strokes instead of losing parts of the picture. Avoid conspicuous straight lines from one person to another when a route near the existing contours is available. Trace every line segment exactly ONCE. NO retracing, NO backtracking, NO overdraw along an existing stroke. Isolated crossings are allowed. Design one open path with exactly two endpoints; use new connecting contours for internal details, never dead-end branches or T junctions. Simplify secondary details when necessary to achieve a genuine single stroke; avoid disconnected outlines, isolated dots, separate eye marks or floating strokes. Keep generous white negative spaces and mostly thin black ink 2-4 pixels at 1024 resolution. NO shading, NO grayscale washes, NO hatching, NO fill areas, NO color, NO texture, NO text or signature. Eyes/hands should remain legible with very few lines. One animated nib must be able to follow the entire drawing without a single pen lift and without revisiting any line segment. Return only the line drawing image at the same aspect ratio.`;

const SPEED_PROFILES=[
 {max:.5,label:'풍부한 선화',summary:'0.5×의 느린 전개에 맞춰 표정·손·핵심 소품의 표현선을 더 허용합니다.',budget:'Allow roughly 24-32 short defining interior contours. Fine expression, hand, clothing and key prop contours are allowed, but still omit texture and repeated marks.'},
 {max:.75,label:'여유 있는 선화',summary:'0.75×에 맞춰 주요 표정과 소품을 살리되 반복 묘사는 줄입니다.',budget:'Allow roughly 18-24 defining interior contours. Preserve expressive faces, hands and important props, while omitting repeated texture.'},
 {max:1,label:'균형 선화',summary:'1.0×에 맞춰 핵심 윤곽과 필요한 표정선을 균형 있게 주문합니다.',budget:'Use roughly 12-18 defining interior contours. Keep only contours needed to read pose, expression and important props.'},
 {max:1.25,label:'간결한 선화',summary:'1.25×에서 선이 몰리지 않도록 내부 묘사와 작은 소품을 줄입니다.',budget:'Use roughly 9-12 defining interior contours. Remove secondary folds, small accessories and repeated object seams.'},
 {max:1.5,label:'단순 선화',summary:'1.5×에서도 읽히도록 실루엣과 핵심 행동만 남깁니다.',budget:'Use roughly 6-9 defining interior contours. Prioritize silhouette, pose, one facial cue per subject and only indispensable props.'},
 {max:2,label:'최소 선화',summary:'2.0×의 빠른 재생을 위해 큰 실루엣과 행동을 설명하는 선만 주문합니다.',budget:'Use no more than about 4-6 defining interior contours. Keep large silhouettes and the single most important action cue; remove minor props and all decorative detail.'}
];

export function speedProfile(value){
 const speed=Number(value);
 if(!Number.isFinite(speed)||speed<.5||speed>2)throw new Error('그리기 속도는 0.5×에서 2.0× 사이여야 합니다.');
 return{speed,...SPEED_PROFILES.find(profile=>speed<=profile.max)};
}

export function promptForSpeed(prompt,value){
 const profile=speedProfile(value);
 return`${prompt}\n\nDRAWING SPEED AND COMPLEXITY ORDER: The animation will be rendered at ${profile.speed.toFixed(2)}x drawing speed. ${profile.budget} Faster playback must remain calm and readable: do not compensate with denser marks, long detours, or extra background objects. This speed-specific complexity order overrides any conflicting request for detail, while all explicitly requested main subjects must remain recognizable.`;
}
// generateContent responseFormat uses protobuf enums; legacy imageConfig
// accepts display strings. Do not reuse one configuration for both formats.
// https://ai.google.dev/api/generate-content#ImageResponseFormat
const aspectEnums={'9:16':'ASPECT_RATIO_NINE_BY_SIXTEEN','16:9':'ASPECT_RATIO_SIXTEEN_BY_NINE','1:1':'ASPECT_RATIO_ONE_BY_ONE'};
export function imageGenerationConfig(model,aspect){
 if(!Object.hasOwn(aspectEnums,aspect))throw new Error('화면 비율은 9:16, 16:9, 1:1 중에서 선택해 주세요.');
 const preview=model.includes('preview'),image={aspectRatio:preview?aspect:aspectEnums[aspect]};
 if(!model.startsWith('gemini-2.5'))image.imageSize=preview?'1K':'IMAGE_SIZE_ONE_K';
 return{responseModalities:['TEXT','IMAGE'],...(preview?{imageConfig:image}:{responseFormat:{image}})};
}
function imagePart(url){const m=/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/.exec(url);if(!m)throw new Error('지원하지 않는 이미지 형식입니다.');return{inlineData:{mimeType:m[1],data:m[2]}};}
export async function generateImage({settings,prompt,aspect,image,signal}){const model=settings.model.trim().replace(/^models\//,'');if(!/^[a-zA-Z0-9._-]+$/.test(model))throw new Error('이미지 모델 ID를 확인해 주세요.');const parts=[{text:prompt}];if(image)parts.push(imagePart(image));const body={contents:[{role:'user',parts}],generationConfig:imageGenerationConfig(model,aspect)};let url,headers={'Content-Type':'application/json'},payload;if(settings.provider==='proxy'){let base;try{base=new URL(settings.proxyUrl);}catch{throw new Error('Cloudflare URL을 확인해 주세요.');}if(base.protocol!=='https:')throw new Error('Cloudflare URL은 https:// 주소를 사용하세요.');url=base.href.replace(/\/$/,'')+'/api/generate';if(!settings.password)throw new Error('접속 비밀번호를 입력해 주세요.');headers.Authorization=`Bearer ${settings.password}`;payload={model,body};}else{if(!settings.key)throw new Error('연결 설정에서 Gemini API 키를 입력해 주세요.');url=`https://generativelanguage.googleapis.com/v1${model.includes('preview')?'beta':''}/models/${encodeURIComponent(model)}:generateContent`;headers['x-goog-api-key']=settings.key;payload=body;}
const controller=new AbortController(),abort=()=>controller.abort(signal?.reason);signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)abort();let timedOut=false;const timer=setTimeout(()=>{timedOut=true;controller.abort();},180000);try{let response;try{response=await fetch(url,{method:'POST',headers,body:JSON.stringify(payload),signal:controller.signal,credentials:'omit',referrerPolicy:'no-referrer'});}catch(e){if(timedOut)throw new Error('생성 요청이 3분 안에 완료되지 않았습니다. 과금 여부를 확인한 뒤 다시 시도해 주세요.');if(e.name==='AbortError')throw e;throw new Error('API에 연결할 수 없습니다. 인터넷 연결, 키 제한 또는 Worker CORS 설정을 확인해 주세요.');}const json=await response.json().catch(()=>({}));if(!response.ok){const hints={400:'요청 또는 이미지 모델 설정을 확인해 주세요.',401:'API 키 또는 접속 비밀번호가 올바르지 않습니다.',403:'키 권한·프로젝트 결제·지역 제한을 확인해 주세요.',404:'모델을 찾지 못했습니다. 연결 설정에서 사용 가능한 모델 ID로 바꿔 주세요.',429:'API 사용량 또는 결제 한도에 도달했습니다. 자동 재시도하지 않았습니다.',502:'생성 서버 응답에 실패했습니다. 과금 여부를 확인한 뒤 다시 시도해 주세요.'};const message=json.error?.message||json.error||'';throw new Error(`${response.status}: ${hints[response.status]||'생성 요청에 실패했습니다.'} ${String(message).slice(0,360)}`);}const candidates=json.candidates||[];for(const candidate of candidates)for(const part of candidate.content?.parts||[]){const data=part.inlineData||part.inline_data;if(!part.thought&&data?.data&&/^image\/(png|jpeg|webp)$/.test(data.mimeType||data.mime_type))return`data:${data.mimeType||data.mime_type};base64,${data.data}`;}const text=candidates.flatMap(c=>c.content?.parts||[]).map(p=>p.text||'').join(' ').slice(0,220);throw new Error('이미지가 반환되지 않았습니다. '+(json.promptFeedback?.blockReason||text||'이미지 생성 모델과 프롬프트를 확인해 주세요.'));}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);}}
