/* Raster -> single-pixel skeleton -> connected, simplified pen paths.
   All processing stays on-device. No image or key leaves this worker. */
const dirs=[[1,0],[1,1],[0,1],[-1,1],[-1,0],[-1,-1],[0,-1],[1,-1]];
const dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
function blur(a,w,h){const b=new Float32Array(a.length),c=new Float32Array(a.length);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let i=y*w+x;b[i]=(a[i-1]+2*a[i]+a[i+1])/4;}for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let i=y*w+x;c[i]=(b[i-w]+2*b[i]+b[i+w])/4;}return c;}
function edges(gray,w,h,detail){const g=blur(gray,w,h),mag=new Float32Array(w*h),angle=new Uint8Array(w*h);for(let y=2;y<h-2;y++)for(let x=2;x<w-2;x++){let i=y*w+x,gx=-g[i-w-1]+g[i-w+1]-2*g[i-1]+2*g[i+1]-g[i+w-1]+g[i+w+1],gy=-g[i-w-1]-2*g[i-w]-g[i-w+1]+g[i+w-1]+2*g[i+w]+g[i+w+1];mag[i]=Math.hypot(gx,gy);let a=(Math.atan2(gy,gx)*180/Math.PI+180)%180;angle[i]=a<22.5||a>=157.5?0:a<67.5?1:a<112.5?2:3;}const high=105-detail*.85,low=high*.42,weak=new Uint8Array(w*h),out=new Uint8Array(w*h),stack=[];for(let y=3;y<h-3;y++)for(let x=3;x<w-3;x++){let i=y*w+x,d=[1,w+1,w,w-1][angle[i]],v=mag[i];if(v>=mag[i-d]&&v>=mag[i+d]&&v>low){weak[i]=1;if(v>=high){out[i]=1;stack.push(i);}}}while(stack.length){const i=stack.pop();for(const [dx,dy]of dirs){const j=i+dy*w+dx;if(weak[j]&&!out[j]){out[j]=1;stack.push(j);}}}return out;}
function thin(a,w,h){let changes=true,iter=0;const remove=[];while(changes&&iter++<90){changes=false;for(let pass=0;pass<2;pass++){remove.length=0;for(let y=2;y<h-2;y++)for(let x=2;x<w-2;x++){const i=y*w+x;if(!a[i])continue;const p=[a[i-w],a[i-w+1],a[i+1],a[i+w+1],a[i+w],a[i+w-1],a[i-1],a[i-w-1]],n=p.reduce((s,v)=>s+v,0);if(n<2||n>6)continue;let transitions=0;for(let k=0;k<8;k++)if(!p[k]&&p[(k+1)%8])transitions++;if(transitions!==1)continue;if(pass===0?(p[0]*p[2]*p[4]||p[2]*p[4]*p[6]):(p[0]*p[2]*p[6]||p[0]*p[4]*p[6]))continue;remove.push(i);}if(remove.length)changes=true;for(const i of remove)a[i]=0;}}return a;}
function simplify(points,tolerance){if(points.length<3)return points;const keep=new Uint8Array(points.length);keep[0]=keep[points.length-1]=1;const stack=[[0,points.length-1]],t2=tolerance*tolerance;while(stack.length){const [a,b]=stack.pop(),p=points[a],q=points[b],dx=q[0]-p[0],dy=q[1]-p[1],len=dx*dx+dy*dy;let max=t2,at=-1;for(let i=a+1;i<b;i++){const v=points[i],t=len?Math.max(0,Math.min(1,((v[0]-p[0])*dx+(v[1]-p[1])*dy)/len)):0,d=(v[0]-p[0]-t*dx)**2+(v[1]-p[1]-t*dy)**2;if(d>max){max=d;at=i;}}if(at>=0){keep[at]=1;stack.push([a,at],[at,b]);}}return points.filter((_,i)=>keep[i]);}
function pathsFrom(a,w,h,detail){const neighbors=i=>{const x=i%w,y=(i/w)|0,out=[];for(let d=0;d<8;d++){const[dx,dy]=dirs[d],nx=x+dx,ny=y+dy,j=i+dy*w+dx;if(nx<1||ny<1||nx>=w-1||ny>=h-1||!a[j])continue; // Suppress redundant diagonal edges next to an orthogonal connection.
if(dx&&dy&&(a[i+dx]||a[i+dy*w]))continue;out.push([j,d]);}return out;};const visited=new Uint8Array(w*h),paths=[];function walk(start,next,d){const ids=[start];visited[start]|=1<<d;visited[next]|=1<<((d+4)%8);let prev=start,cur=next;for(let step=0;step<w*h;step++){ids.push(cur);let ns=neighbors(cur).filter(([j,k])=>j!==prev&&!(visited[cur]&(1<<k)));if(!ns.length)break; // At branches, continue along the least abrupt turn; visit side branches later.
if(ns.length>1){const vx=cur%w-prev%w,vy=((cur/w)|0)-((prev/w)|0);ns.sort(([j],[k])=>{let ax=j%w-cur%w,ay=((j/w)|0)-((cur/w)|0),bx=k%w-cur%w,by=((k/w)|0)-((cur/w)|0);return (bx*vx+by*vy)/Math.hypot(bx,by)-(ax*vx+ay*vy)/Math.hypot(ax,ay);});}
const [n,nd]=ns[0];visited[cur]|=1<<nd;visited[n]|=1<<((nd+4)%8);prev=cur;cur=n;if(cur===start){ids.push(cur);break;}}
const pts=ids.map(i=>[i%w,(i/w)|0]);let length=0;for(let i=1;i<pts.length;i++)length+=dist(pts[i-1],pts[i]);if(length>=Math.max(5,16-detail*.15))paths.push(simplify(pts,Math.max(.45,1.6-detail*.012)));}
const ends=[],other=[];for(let y=2;y<h-2;y++)for(let x=2;x<w-2;x++){let i=y*w+x;if(a[i]){const ns=neighbors(i);(ns.length===1?ends:other).push(i);}}for(const i of [...ends,...other])for(const [j,d]of neighbors(i))if(!(visited[i]&(1<<d)))walk(i,j,d);return paths;}
self.onmessage=e=>{try{const{pixels,width:w,height:h,mode='auto',detail=55}=e.data,gray=new Float32Array(w*h);let whites=0;for(let i=0;i<gray.length;i++){const j=i*4,alpha=pixels[j+3]/255;gray[i]=(pixels[j]*.2126+pixels[j+1]*.7152+pixels[j+2]*.0722)*alpha+255*(1-alpha);if(gray[i]>228)whites++;}const actualMode=mode==='auto'?(whites/gray.length>.55?'line':'photo'):mode;self.postMessage({stage:'선을 분리하고 있습니다.'});let mask;if(actualMode==='line'){mask=new Uint8Array(w*h);const threshold=112+detail*1.42;for(let y=3;y<h-3;y++)for(let x=3;x<w-3;x++){const i=y*w+x;mask[i]=gray[i]<threshold?1:0;}}else mask=edges(gray,w,h,detail);self.postMessage({stage:'선의 중심을 따라 획을 연결하고 있습니다.'});thin(mask,w,h);let paths=pathsFrom(mask,w,h,detail);if(paths.length>4500){paths.sort((a,b)=>b.length-a.length);paths=paths.slice(0,4500);}if(!paths.length)throw new Error('그릴 수 있는 선을 찾지 못했습니다. 더 선명한 그림이나 세부 묘사 값을 높여 사용해 주세요.');let x0=w,y0=h,x1=0,y1=0;for(const path of paths)for(const[x,y]of path){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}self.postMessage({result:{paths,width:w,height:h,bounds:{x:x0,y:y0,w:Math.max(1,x1-x0),h:Math.max(1,y1-y0)},mode:actualMode}});}catch(error){self.postMessage({error:error.message});}};
