import test from 'node:test';
import assert from 'node:assert/strict';
import {generateImage,imageGenerationConfig} from '../js/gemini.js';
import worker from '../cloudflare/worker.js';
// Contract values from the REST ImageResponseFormat / ImageConfig reference:
// https://ai.google.dev/api/generate-content#ImageResponseFormat
const ratios={'9:16':'ASPECT_RATIO_NINE_BY_SIXTEEN','16:9':'ASPECT_RATIO_SIXTEEN_BY_NINE','1:1':'ASPECT_RATIO_ONE_BY_ONE'};
const img='data:image/png;base64,aW1hZ2U=';
const success=()=>new Response(JSON.stringify({candidates:[{content:{parts:[{inlineData:{mimeType:'image/png',data:'aW1hZ2U='}}]}}]}),{headers:{'Content-Type':'application/json'}});
function contract(body,preview=false,model='gemini-3.1-flash-image'){
 const config=body.generationConfig;assert.deepEqual(config.responseModalities,['TEXT','IMAGE']);
 if(preview){assert(!config.responseFormat);assert(Object.hasOwn(ratios,config.imageConfig.aspectRatio));if(!model.startsWith('gemini-2.5'))assert.equal(config.imageConfig.imageSize,'1K');}
 else{assert(!config.imageConfig);assert(Object.values(ratios).includes(config.responseFormat.image.aspectRatio),'v1 requires an AspectRatio enum');if(!model.startsWith('gemini-2.5'))assert.equal(config.responseFormat.image.imageSize,'IMAGE_SIZE_ONE_K','v1 requires an ImageSize enum');}
}
async function mockFetch(mock,run){const before=globalThis.fetch;globalThis.fetch=mock;try{return await run();}finally{globalThis.fetch=before;}}
const settings={provider:'direct',key:'NOT_A_REAL_KEY',model:'gemini-3.1-flash-image'};
test('the previous 9:16/1K responseFormat packet violates the REST contract',()=>{assert.throws(()=>contract({generationConfig:{responseModalities:['TEXT','IMAGE'],responseFormat:{image:{aspectRatio:'9:16',imageSize:'1K'}}}}));});
test('all UI aspect ratios and stable image models send enum values to v1',async()=>{for(const model of['gemini-3.1-flash-image','gemini-3.1-flash-lite-image','gemini-3-pro-image'])for(const aspect of Object.keys(ratios)){let calls=0;await mockFetch(async(url,init)=>{calls++;assert.equal(new URL(url).pathname,`/v1/models/${model}:generateContent`);assert.equal(init.headers['x-goog-api-key'],settings.key);assert(!url.includes(settings.key));const body=JSON.parse(init.body);contract(body);assert.equal(body.generationConfig.responseFormat.image.aspectRatio,ratios[aspect]);return success();},async()=>assert.equal(await generateImage({settings:{...settings,model},prompt:'test',aspect}),img));assert.equal(calls,1);}});
test('image editing preserves the source image and uses the same valid configuration',async()=>{await mockFetch(async(_,init)=>{const body=JSON.parse(init.body);contract(body);assert.deepEqual(body.contents[0].parts[1],{inlineData:{mimeType:'image/png',data:'aW1hZ2U='}});return success();},async()=>assert.equal(await generateImage({settings,prompt:'trace',image:img,aspect:'9:16'}),img));});
test('preview endpoint retains legacy imageConfig string values',async()=>{await mockFetch(async(url,init)=>{assert(url.includes('/v1beta/models/gemini-3.1-flash-image-preview:generateContent'));const body=JSON.parse(init.body);contract(body,true);assert.equal(body.generationConfig.imageConfig.aspectRatio,'16:9');return success();},()=>generateImage({settings:{...settings,model:'models/gemini-3.1-flash-image-preview'},prompt:'test',aspect:'16:9'}));});
test('Gemini 2.5 omits its unsupported image-size override',()=>{const c=imageGenerationConfig('gemini-2.5-flash-image','1:1');assert.equal(c.responseFormat.image.aspectRatio,'ASPECT_RATIO_ONE_BY_ONE');assert.equal(c.responseFormat.image.imageSize,undefined);});
test('invalid UI ratios fail before any API request',async()=>{let calls=0;await mockFetch(async()=>{calls++;return success();},async()=>assert.rejects(generateImage({settings,prompt:'test',aspect:'unsupported'}),/화면 비율/));assert.equal(calls,0);});
test('400 errors are surfaced once without a paid fallback or retry',async()=>{let calls=0;await mockFetch(async()=>{calls++;return new Response(JSON.stringify({error:{message:'Invalid test request'}}),{status:400});},async()=>assert.rejects(generateImage({settings,prompt:'test',aspect:'9:16'}),/400:/));assert.equal(calls,1);});
test('browser proxy requests carry valid enums and no Google API key',async()=>{await mockFetch(async(url,init)=>{assert.equal(url,'https://worker.test/api/generate');assert.equal(init.headers.Authorization,'Bearer TEST_PASSWORD');assert(!init.headers['x-goog-api-key']);contract(JSON.parse(init.body).body);return success();},()=>generateImage({settings:{...settings,provider:'proxy',proxyUrl:'https://worker.test',password:'TEST_PASSWORD'},prompt:'test',aspect:'16:9'}));});
const env={GEMINI_API_KEY:'TEST_SERVER_KEY',APP_PASSWORD:'TEST_PASSWORD',ALLOWED_ORIGINS:'https://example.github.io',RATE_LIMITER:{limit:async()=>({success:true})}};
const req=(value,model='gemini-3.1-flash-image',password=env.APP_PASSWORD,origin=env.ALLOWED_ORIGINS)=>new Request('https://worker.test/api/generate',{method:'POST',headers:{Origin:origin,Authorization:'Bearer '+password,'Content-Type':'application/json'},body:JSON.stringify({model,body:{contents:[{parts:[{text:'test'}]}],generationConfig:{responseFormat:{image:{aspectRatio:value,imageSize:'IMAGE_SIZE_FOUR_K'}}}}})});
test('Worker accepts both old and new clients, preserves all aspect ratios, and caps size',async()=>{for(const [aspect,code]of Object.entries(ratios))for(const value of[aspect,code])await mockFetch(async(url,init)=>{assert(url.includes('/v1/'));assert.equal(init.headers['x-goog-api-key'],'TEST_SERVER_KEY');const body=JSON.parse(init.body);contract(body);assert.equal(body.generationConfig.responseFormat.image.aspectRatio,code);return success();},async()=>assert.equal((await worker.fetch(req(value),env)).status,200));});
test('Worker converts enum inputs back to strings for preview models',async()=>{await mockFetch(async(url,init)=>{assert(url.includes('/v1beta/'));const body=JSON.parse(init.body);contract(body,true);assert.equal(body.generationConfig.imageConfig.aspectRatio,'16:9');return success();},async()=>assert.equal((await worker.fetch(req('ASPECT_RATIO_SIXTEEN_BY_NINE','gemini-3.1-flash-image-preview'),env)).status,200));});
test('Worker rejects invalid ratios and credentials without reaching Google',async()=>{let calls=0;await mockFetch(async()=>{calls++;return success();},async()=>{assert.equal((await worker.fetch(req('invalid'),env)).status,400);assert.equal((await worker.fetch(req('9:16',undefined,'wrong'),env)).status,401);assert.equal((await worker.fetch(req('9:16',undefined,undefined,'https://evil.invalid'),env)).status,403);});assert.equal(calls,0);});
