// Deploy separately from GitHub Pages. Secrets NEVER belong in the static app.
const models=['gemini-3.1-flash-image','gemini-3.1-flash-lite-image','gemini-3-pro-image','gemini-2.5-flash-image','gemini-3.1-flash-image-preview'];
// Accept both old display values and the fixed client's v1 enum values.
const aspects={'9:16':'ASPECT_RATIO_NINE_BY_SIXTEEN','16:9':'ASPECT_RATIO_SIXTEEN_BY_NINE','1:1':'ASPECT_RATIO_ONE_BY_ONE'};
function outputConfig(model,value){
 const aspect=Object.keys(aspects).find(k=>value===k||value===aspects[k])||(value==null?'9:16':null);
 if(!aspect)return null;
 const preview=model.includes('preview'),image={aspectRatio:preview?aspect:aspects[aspect]};
 if(!model.startsWith('gemini-2.5'))image.imageSize=preview?'1K':'IMAGE_SIZE_ONE_K';
 return{responseModalities:['TEXT','IMAGE'],...(preview?{imageConfig:image}:{responseFormat:{image}})};
}
const hash=s=>crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));
async function equal(a,b){const x=new Uint8Array(await hash(a)),y=new Uint8Array(await hash(b));let n=0;for(let i=0;i<x.length;i++)n|=x[i]^y[i];return n===0;}
async function limitedJSON(request,max){const reader=request.body?.getReader();if(!reader)throw new Error('Empty body');const chunks=[];let size=0;while(true){const{value,done}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new Error('Request too large');}chunks.push(value);}const out=new Uint8Array(size);let pos=0;for(const c of chunks){out.set(c,pos);pos+=c.length;}return JSON.parse(new TextDecoder().decode(out));}
export default{async fetch(request,env){const origin=request.headers.get('Origin')||'',allowed=(env.ALLOWED_ORIGINS||'').split(',').map(s=>s.trim()).filter(Boolean),isAllowed=allowed.includes(origin),cors={'Access-Control-Allow-Origin':isAllowed?origin:'null','Vary':'Origin','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};const json=(status,message)=>new Response(JSON.stringify({error:{message}}),{status,headers:{...cors,'Content-Type':'application/json'}});if(!isAllowed)return json(403,'Origin is not allowed.');if(new URL(request.url).pathname!=='/api/generate')return json(404,'Not found.');if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...cors,'Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Max-Age':'600'}});if(request.method!=='POST')return json(405,'POST required.');if(!env.GEMINI_API_KEY||!env.APP_PASSWORD||!env.RATE_LIMITER)return json(503,'Worker secrets or rate limiter are missing.'); // Fail closed if the limiter was not configured.
const ip=request.headers.get('CF-Connecting-IP')||'unknown';if(!(await env.RATE_LIMITER.limit({key:'attempt:'+ip})).success)return json(429,'Too many requests.');const auth=request.headers.get('Authorization')||'';if(auth.length>512||!auth.startsWith('Bearer ')||!await equal(auth.slice(7),env.APP_PASSWORD))return json(401,'Incorrect password.');if(!(await env.RATE_LIMITER.limit({key:'generation:shared-password'})).success)return json(429,'Generation rate limit reached.');let data;try{data=await limitedJSON(request,20*1024*1024);}catch{return json(400,'Invalid or oversized request.');}const allowModels=(env.ALLOWED_MODELS||models.join(',')).split(',').map(s=>s.trim());if(!allowModels.includes(data.model))return json(400,'Model is not allowed.');const parts=data.body?.contents?.[0]?.parts;if(!Array.isArray(parts)||parts.length<1||parts.length>2)return json(400,'Invalid image request.');const clean=[];for(const p of parts){if(typeof p.text==='string'&&p.text.length<=16000)clean.push({text:p.text});else if(p.inlineData&&['image/png','image/jpeg','image/webp'].includes(p.inlineData.mimeType)&&typeof p.inlineData.data==='string'&&p.inlineData.data.length<19*1024*1024&&/^[A-Za-z0-9+/=]+$/.test(p.inlineData.data))clean.push({inlineData:{mimeType:p.inlineData.mimeType,data:p.inlineData.data}});else return json(400,'Invalid image parts.');}const imageSettings=data.body.generationConfig?.responseFormat?.image||data.body.generationConfig?.imageConfig||{},generationConfig=outputConfig(data.model,imageSettings.aspectRatio);if(!generationConfig)return json(400,'Invalid aspect ratio.');const body={contents:[{role:'user',parts:clean}],generationConfig};try{const response=await fetch(`https://generativelanguage.googleapis.com/v1${data.model.includes('preview')?'beta':''}/models/${data.model}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':env.GEMINI_API_KEY},body:JSON.stringify(body),signal:AbortSignal.timeout(175000)});return new Response(response.body,{status:response.status,headers:{...cors,'Content-Type':'application/json'}});}catch{return json(502,'Generation server timed out or could not be reached.');}}};
